FROM python:3.9-slim as builder

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


FROM python:3.9-alpine

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY . .

EXPOSE 5001

# Set environment variables
ENV AWS_ACCESS_KEY_ID="AKIAXLEKZJVVSTPGSZ6O"
ENV AWS_SECRET_ACCESS_KEY="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"
ENV AWS_DEFAULT_REGION="us-east-1"

# Run the application
CMD ["python", "app.py"]